### ISSUE TITLE
HMR exception in Single File Components

### ISSUE THREAD

**Issue by npulidom** [TheBojda/parcel-vue2#2]
Hi @TheBojda! Nice work here, the plugin compiles Vue2 SFCs correctly, I haven't encountered yet any parcel errors in compiling time, and I've already tested with a couple of medium projects. The thing is, I noticed that an exception is raising when trying to save a SFC when the HMR engine is running, and failing to remount the component in the application.

```js
__VUE_HMR_RUNTIME__ is not defined  at eval (eval at hmrApply)
```
screenshot:
https://pasteboard.co/BEdhpUZyBLE2.png

This exception only occurs in SFC components, modules and styles files are updated correctly. I updated an example project in case you want to look further, the branch is `parcel-2`.
https://github.com/npulidom/vue-parcel

Thank you for all the great work.

**Comment by TheBojda** [comment]
Hello @npulidom ! Thank you for the great report! I'm not a parcel or vue expert, but try to investigate it soon.  

btw, if anybody has a good solution, ideas and PRs are really appreciated

**Comment by TheBojda** [comment]
I've checked this HMR thing. It is a feature of vue3 and I didn't find an easy solution for vue2. Now I've removed the HMR part, and replaced by location.reload. I know, it's not real HMR, but a working solution, and far better than nothing. :)

**Comment by npulidom** [comment]
Thanks @TheBojda !
Maybe implementing the [vue2-hot-reload-api](https://github.com/vuejs/vue-hot-reload-api) to this plugin could be a solution :thinking: 


I'll be looking further

**Comment by TheBojda** [comment]
Thank you @npulidom . It looks like something that is needed. I'll take a look on it.

**Comment by TheBojda** [comment]
I've published a new version (v0.1.7), and it looks working. Can you take a try with it?

**Comment by moonpyk** [comment]
@TheBojda it works ! I made a pull request (#4) to spice things up

**Comment by TheBojda** [comment]
Cool! Thank you for the help! 

May I close this issue?

**Comment by npulidom** [comment]
Great job @TheBojda @moonpyk, HMR works perfectly!

**Comment by TheBojda** [comment]
Cool! Then I close this issue. 

Yay, first successfully closed issue! :)
