### ISSUE TITLE
Vue 2.7 support

### ISSUE THREAD

**Issue by tno2007** [TheBojda/parcel-vue2#7]
Thanks for your amazing work on this plugin!

Just wondering would you have time to update this to Vue 2.7?

--

The v2.7 update brought some amazing things:
- script setup built in
- vue-composition-api built in

I'm using 2.7 and it works. It just does not play nicely with script setup.

For example...
```vue
<script setup lang="ts">
const props = defineProps({
  dataStyle: {
    type: String,
    default: "expand-left",
  }
})
</script>
<template>
    <div>{{ props }}</div>
</template>
```

yields error...

```
vue.runtime.esm.js:4625 [Vue warn]: Property or method "props" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://v2.vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.
```

**Comment by TheBojda** [comment]
I personally started to use Vue3, but you can try to add Vue 2.7 support. The transformer simply calls the Vue template compiler. So, if it is API compatible with the previous version, then changing the version in the package.json in https://github.com/TheBojda/parcel-vue2/tree/main/parcel-transformer-vue2 can be enough.

**Comment by tno2007** [comment]
I am currently upgrading to Vue 3. 
2.7 is just an immediately step, and Parcel solved some dev problems for me (ie. up front bundling dev bundling) compared to vite.

I will try your suggestion. Thank you.

Worse case, I'll can just use the Vue's "setup and return" format and finish my interim upgrade. (removing context.root etc.) then I can upgrade straight to v3.

**Comment by tno2007** [comment]
I tried upgrading to vue-template-compiler 2.7 in this lib, but it did not work.
Eventually I just copied my src code to a vite vue2 project. I'm happy for now. Thanks.
