### ISSUE TITLE
Support VueJS 2.7.x

### ISSUE THREAD

**Issue by raisiqueira** [TheBojda/parcel-vue2#8]
Hey folks, I found this package in [this issue](https://github.com/parcel-bundler/parcel/issues/6153) and I would like to know if there's any plan to support the newest version of Vue 2 (the 2.7.x) and the Parcel (2.11.x).

**Comment by TheBojda** [comment]
Hi! I personally changed to vue 3, and use it in my projects, so I didn't use my plugin in my projects a long time ago.

Maybe it works with vue2.7. Have you tried it? Does the plugin throw an error?

**Comment by raisiqueira** [comment]
Hi @TheBojda, thanks for answering, I haven't tried yet. I just updated the Parcel version from 2.2.1 to the last one (2.11.0), but now It is raising an error when I run the `parcel watch` command:

![CleanShot 2024-01-24 at 13 53 58](https://github.com/TheBojda/parcel-vue2/assets/2914170/f65ccac8-fc09-4bda-87d6-63114f53dfab)

I believe that this error is [related to the Parcel](https://github.com/parcel-bundler/parcel/issues/6310), and not this custom transformer. First, I'll focus on solving this error, and then try to use the transformer with Vue 2.7. I'll keep you informed. Thanks.

**Comment by TheBojda** [comment]
Yep, it looks like parcel related.

Btw, when I created this plugin I used the original Vue 3 plugin and modified it a little. So if you cannot fix the parcel issue, maybe you can do the same and modify the vue3 plugin to make vue2 compatible.

Or you can change to vue 3 like me. :)
